### ISSUE TITLE
mcrypt / openssl

### ISSUE THREAD

**Issue by andreaslarssen** [ambta/DoctrineEncryptBundle#3]
Nice bundle, only one question though:

Isn't libmcrypt which mcrypt is dependent on, which in turn your bundle is dependent on deprecated and unmaintained since 2007? 

Would it be an idea to use openssl instead?

**Comment by ambta** [comment]
Hi Andreas,

Thank you for your comment.

It is indeed in consideration to use OpenSSL. Not because of the deprecation of Mcrypt but because the performance of it. None of the functions we are currently using are deprecated. There are currently no critical issues regarding to libmcrypt. 

You can easily add an custom encryptor class for now. More about that can be found here:
https://github.com/ambta/DoctrineEncryptBundle/blob/master/Resources/doc/custom_encryptor.md

Version 3 which will be coming soon and wil probably use openSSL.

Related information:

PHP Mcrypt documentation
http://php.net/manual/en/book.mcrypt.php

Deceprecation of mcrypt_cbc, mcrypt_cfb, mcrypt_ecb and mcrypt_ofb
http://php.net/manual/en/migration55.deprecated.php

Performance of OpenSSL
https://jrm.cc/posts/php-aes-openssl/

**Comment by andreaslarssen** [comment]
Thanks for the info, sounds like a good plan.
